/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import com.toedter.calendar.JDateChooser;
import javax.swing.DefaultListModel;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author CRISTHIAN. S
 */
public class frmRegPaciente extends javax.swing.JInternalFrame {

    DefaultListModel ModeloLista;
    
    public frmRegPaciente() {
        initComponents();
        ModeloLista = new DefaultListModel();
        //listTelefonoP.setModel(ModeloLista);//Modifique el modelo de la listatelefono para acceder a los metodos del DefaultListModel
    }

    public JButton getBtnActPac() {
        return BtnActPac;
    }

    public void setBtnActPac(JButton BtnActPac) {
        this.BtnActPac = BtnActPac;
    }

    public JTextField getTxtTipoID() {
        return txtTipoID;
    }

    public void setTxtTipoID(JTextField txtTipoID) {
        this.txtTipoID = txtTipoID;
    }
   
    public JButton getBtnMunicipio() {
        return btnMunicipio;
    }

    public void setBtnMunicipio(JButton btnMunicipio) {
        this.btnMunicipio = btnMunicipio;
    }
    
    

    public JButton getBtnRegistrarP() {
        return btnRegistrarP;
    }

    public void setBtnRegistrarP(JButton btnRegistrarP) {
        this.btnRegistrarP = btnRegistrarP;
    }

    public JButton getBtnTipoID() {
        return btnTipoID;
    }

    public void setBtnTipoID(JButton btnTipoID) {
        this.btnTipoID = btnTipoID;
    }

  

    public JTextField getTxtIdP() {
        return txtIdP;
    }

    public void setTxtIdP(JTextField txtIdP) {
        this.txtIdP = txtIdP;
    }

    public JTextField getTxtMunicipioP() {
        return txtMunicipioP;
    }

    public void setTxtMunicipioP(JTextField txtMunicipioP) {
        this.txtMunicipioP = txtMunicipioP;
    }

    public JTextField getTxtNombreP() {
        return txtNombreP;
    }

    public void setTxtNombreP(JTextField txtNombreP) {
        this.txtNombreP = txtNombreP;
    }


    public JDateChooser getDataFecha() {
        return DataFecha;
    }

    public void setDataFecha(JDateChooser DataFecha) {
        this.DataFecha = DataFecha;
    }

    public JButton getBtnAsigTelPac() {
        return btnAsigTelPac;
    }

    public void setBtnAsigTelPac(JButton btnAsigTelPac) {
        this.btnAsigTelPac = btnAsigTelPac;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtIdP = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtMunicipioP = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtNombreP = new javax.swing.JTextField();
        btnRegistrarP = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        DataFecha = new com.toedter.calendar.JDateChooser();
        btnMunicipio = new javax.swing.JButton();
        btnTipoID = new javax.swing.JButton();
        btnAsigTelPac = new javax.swing.JButton();
        txtTipoID = new javax.swing.JTextField();
        BtnActPac = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setIconifiable(true);
        setTitle("Registro del paciente");

        jLabel2.setText("Identificación");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setText("Registro del Paciente");

        jLabel4.setText("Tipo");

        jLabel5.setText("Municipio");

        txtMunicipioP.setEditable(false);

        jLabel1.setText("Nombre");

        btnRegistrarP.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnRegistrarP.setText("Registrar Paciente");

        jLabel8.setText("Fecha de nacimiento");

        btnMunicipio.setText("Añadir Municipio");

        btnTipoID.setText("Escojer tipo de ID");

        btnAsigTelPac.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnAsigTelPac.setText("Asignar Telefonos");
        btnAsigTelPac.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnAsigTelPac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAsigTelPacActionPerformed(evt);
            }
        });

        txtTipoID.setEditable(false);

        BtnActPac.setBackground(new java.awt.Color(255, 255, 255));
        BtnActPac.setFont(new java.awt.Font("Eras Medium ITC", 0, 11)); // NOI18N
        BtnActPac.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/actualizar.png"))); // NOI18N
        BtnActPac.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BtnActPac.setFocusable(false);
        BtnActPac.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BtnActPac.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jLabel3.setFont(new java.awt.Font("Palatino Linotype", 0, 14)); // NOI18N
        jLabel3.setText("Actualizar Paciente");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(143, 143, 143)
                        .addComponent(jLabel6))
                    .addComponent(btnRegistrarP, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAsigTelPac, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtNombreP, javax.swing.GroupLayout.DEFAULT_SIZE, 226, Short.MAX_VALUE)
                                    .addComponent(txtIdP)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(DataFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(20, 20, 20)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(txtMunicipioP, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(btnMunicipio))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(txtTipoID, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(btnTipoID)))))))
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BtnActPac, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtNombreP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtIdP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(btnTipoID)
                            .addComponent(txtTipoID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtMunicipioP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnMunicipio))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(DataFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BtnActPac, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRegistrarP, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnAsigTelPac, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAsigTelPacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAsigTelPacActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAsigTelPacActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnActPac;
    private com.toedter.calendar.JDateChooser DataFecha;
    private javax.swing.JButton btnAsigTelPac;
    private javax.swing.JButton btnMunicipio;
    private javax.swing.JButton btnRegistrarP;
    private javax.swing.JButton btnTipoID;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField txtIdP;
    private javax.swing.JTextField txtMunicipioP;
    private javax.swing.JTextField txtNombreP;
    private javax.swing.JTextField txtTipoID;
    // End of variables declaration//GEN-END:variables
}
